/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("daily_planner.kotlin-application-conventions")
    kotlin("jvm") version "1.8.0"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    //implementation(project(":stubs"))
    // This dependency is used by the application.
    listOf(
        "armeria",
        "armeria-brave",
        "armeria-grpc",
        "armeria-jetty9",
        "armeria-kafka",
        "armeria-logback",
        "armeria-zookeeper3").forEach { implementation("com.linecorp.armeria:${it}:1.22.0") }

    implementation("com.google.guava:guava:31.1-jre")
    implementation("com.google.inject:guice:5.1.0")
    api(project( ":stubs"))

    // Logging
    runtimeOnly("ch.qos.logback:logback-classic:1.4.6")
    runtimeOnly("org.slf4j:log4j-over-slf4j:2.0.5")
    implementation("io.github.oshai:kotlin-logging-jvm:4.0.0-beta-11")
    implementation("io.micrometer:micrometer-registry-prometheus:1.10.5")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    implementation("com.linecorp.armeria:armeria-kotlin:1.22.1")
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.0")
    implementation("org.apache.kafka:kafka-clients:3.4.0")

    //DB dependencies
    //pg
    implementation("org.postgresql:postgresql:42.6.0")
    //hikaricp
    implementation("com.zaxxer:HikariCP:5.0.1")
    //jdbi
    implementation("org.jdbi:jdbi3-kotlin:3.38.0-rc2")
    implementation("org.jdbi:jdbi3-kotlin-sqlobject:3.38.0-rc2")
    implementation("org.jdbi:jdbi3-postgres:3.38.0-rc2")
    implementation("org.jdbi:jdbi3-guice:3.37.1")
    implementation("org.jdbi:jdbi3-jackson2:3.38.0-rc2")

}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(15))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("1.8.0")

            dependencies {
                // Use newer version of JUnit Engine for Kotlin Test
                implementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
            }
        }
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}



tasks.withType<Jar>() {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes["Main-Class"] = "daily_planner.app.AppKt"
    }

    from(sourceSets.main.get().output)
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) { it } else { zipTree((it)) }})
}


application {
    // Define the main class for the application.
    mainClass.set("daily_planner.app.AppKt")
}
