/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("daily_planner.kotlin-library-conventions")
    kotlin("jvm") version "1.8.0"
    application
}

dependencies {
    api(project(":stubs"))

    listOf(
        "armeria",
        "armeria-grpc",
        "armeria-jetty9",
        "armeria-kafka",
        "armeria-kotlin",
        "armeria-logback",
        "armeria-retrofit2",
        "armeria-zookeeper3").forEach { implementation("com.linecorp.armeria:${it}:1.23.1") }

    implementation("org.apache.kafka:kafka-clients:3.4.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.2")
    implementation("io.micrometer:micrometer-registry-prometheus:1.10.5")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("io.github.oshai:kotlin-logging-jvm:4.0.0-beta-11")
    runtimeOnly("ch.qos.logback:logback-classic:1.4.6")
    runtimeOnly("org.slf4j:log4j-over-slf4j:2.0.5")
    implementation("com.google.inject:guice:5.1.0")

    //date
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.2")

}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
repositories {
    mavenCentral()
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

tasks.withType<Jar>() {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes["Main-Class"] = "daily_planner.kafkaconsumerapp.KafkaConsumerMainKt"
    }

    from(sourceSets.main.get().output)
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) { it } else { zipTree((it)) }})
}

application {
    // Define the main class for the application.
    mainClass.set("daily_planner.kafkaconsumerapp.KafkaConsumerMainKt")
}
