apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-http-app-deployment
  labels:
    app: todo-http-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-http-app
  template:
    metadata:
      labels:
        app: todo-http-app
    spec:
      containers:
        - name: todo-http-app
          image: rafikiass/todo-http-client-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: todo-http-app
spec:
  type: NodePort
  selector:
    name: todo-http-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081