apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-app-deployment
  labels:
    app: kafka-consumer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-consumer-app
  template:
    metadata:
      labels:
        app: kafka-consumer-app
    spec:
      containers:
        - name: kafka-consumer-app
          image: rafikiass/kafka-consumer-app
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-app
spec:
  type: NodePort
  selector:
    name: kafka-consumer-app
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087