import com.google.protobuf.gradle.id

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("daily_planner.kotlin-library-conventions")
    kotlin("jvm") version "1.7.10"
    id("com.google.protobuf") version "0.9.2"
    //application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    //kotlin grpc protos

    compileOnly("io.grpc:grpc-stub:1.53.0")
    implementation("io.grpc:grpc-protobuf:1.53.0")
    implementation("com.google.protobuf:protobuf-java-util:3.22.2")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    api("com.google.protobuf:protobuf-kotlin:3.22.2")
    api("io.grpc:grpc-kotlin-stub:1.3.0")
    implementation("org.jdbi:jdbi3-kotlin:3.38.0-rc2")
}

sourceSets {
    val main by getting { }
    main.java.srcDirs("build/generated/source/proto/main/java")
    main.java.srcDirs("build/generated/source/proto/main/grpc")
    main.java.srcDirs("build/generated/source/proto/main/kotlin")
    main.java.srcDirs("build/generated/source/proto/main/grpckt")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(15))
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.12"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.53.0"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:1.3.0:jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                id("grpc")
                id("grpckt")
            }
            it.builtins {
                id("kotlin")
            }
        }
    }
}